#OnlineUTE Session Config
#Sat Apr 04 17:56:48 ICT 2026
account.id=1
profile.id=1
session.loggedIn=true
profile.fullName=H\u1EC7 th\u1ED1ng Qu\u1EA3n tr\u1ECB
profile.code=AD001
account.role=ADMIN
profile.type=ADMIN
