#OnlineUTE Session Config
#Tue Mar 31 02:03:58 ICT 2026
account.id=286
account.username=24110777
profile.id=259
session.loggedIn=true
profile.fullName=kgndgf
profile.code=24110777
account.role=STUDENT
profile.type=STUDENT
