#OnlineUTE Session Config
#Thu Apr 09 19:40:41 ICT 2026
account.id=13
profile.id=10
session.loggedIn=true
profile.fullName=TS. D\u01B0\u01A1ng Thu S\u01A1n
profile.code=gv011
account.role=LECTURER
profile.type=LECTURER
